# Generated by Django 5.0.1 on 2024-01-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_reciever_name_address_receiver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_no',
            field=models.CharField(),
        ),
    ]
