# Generated by Django 5.0.1 on 2024-02-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_section_sectionitems_sectionsectionitemsthrough_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_type',
        ),
        migrations.AddField(
            model_name='section',
            name='section_file',
            field=models.FileField(blank=True, null=True, upload_to='media/section_files/'),
        ),
    ]
